"""LLM 设置默认模板 — llm_settings.json 缺省模板生成。

职责：
  提供 _get_default_llm_settings_template() 函数，返回带中文分组注释的
  llm_settings.json 模板字符串。首次初始化时由 _core.py 的
  _ensure_llm_settings_file() 调用写入磁盘。
"""


def _get_default_llm_settings_template() -> str:
    """返回带分组注释的默认 llm_settings.json 模板字符串。

    支持 // 注释风格，由 _strip_json_comments() 剥离后解析。
    """
    return (
        '{\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 全局设置\n'
        '  // ═══════════════════════════════════════════\n'
        '  "max_retries": 2,\n'
        '  "llm_max_concurrency": 3,\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 模块开关 — 控制各 LLM 分析功能的启用/停用\n'
        '  // ═══════════════════════════════════════════\n'
        '  "enabled_llm": {\n'
        '    "global_macro": true,\n'
        '    "expert_review": true,\n'
        '    "health_check": true,\n'
        '    "penetration_deep": true,\n'
        '    "news_correlation": false\n'
        '  },\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 全球政经局势 — global_macro\n'
        '  // ═══════════════════════════════════════════\n'
        '  "system_prompt_global_macro": null,\n'
        '  "model_global_macro": null,\n'
        '  "temperature_global_macro": 0.3,\n'
        '  "max_tokens_global_macro": 2048,\n'
        '  "timeout_global_macro": 60,\n'
        '  "cache_enabled_global_macro": true,\n'
        '  "output_brief_global_macro": false,\n'
        '  "thinking_enabled_global_macro": false,\n'
        '  "thinking_budget_global_macro": 4000,\n'
        '  "reasoning_effort_global_macro": "high",\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 智囊团深度复盘 — expert_review\n'
        '  // ═══════════════════════════════════════════\n'
        '  "system_prompt_expert_review": null,\n'
        '  "model_expert_review": null,\n'
        '  "temperature_expert_review": 0.8,\n'
        '  "max_tokens_expert_review": 8192,\n'
        '  "timeout_expert_review": 120,\n'
        '  "cache_enabled_expert_review": true,\n'
        '  "output_brief_expert_review": false,\n'
        '  "thinking_enabled_expert_review": true,\n'
        '  "thinking_budget_expert_review": 16000,\n'
        '  "reasoning_effort_expert_review": "high",\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 持仓体检报告 — health_check\n'
        '  // ═══════════════════════════════════════════\n'
        '  "system_prompt_health_check": null,\n'
        '  "model_health_check": null,\n'
        '  "temperature_health_check": 0.5,\n'
        '  "max_tokens_health_check": 4096,\n'
        '  "timeout_health_check": 120,\n'
        '  "cache_enabled_health_check": true,\n'
        '  "output_brief_health_check": false,\n'
        '  "thinking_enabled_health_check": true,\n'
        '  "thinking_budget_health_check": 12000,\n'
        '  "reasoning_effort_health_check": "high",\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 穿透深度分析 — penetration_deep\n'
        '  // ═══════════════════════════════════════════\n'
        '  "system_prompt_penetration_deep": null,\n'
        '  "model_penetration_deep": null,\n'
        '  "temperature_penetration_deep": 0.4,\n'
        '  "max_tokens_penetration_deep": 4096,\n'
        '  "timeout_penetration_deep": 90,\n'
        '  "cache_enabled_penetration_deep": true,\n'
        '  "output_brief_penetration_deep": false,\n'
        '  "thinking_enabled_penetration_deep": false,\n'
        '  "thinking_budget_penetration_deep": 8000,\n'
        '  "reasoning_effort_penetration_deep": "high",\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 财经新闻热点与持仓关联分析 — news_correlation\n'
        '  // （注：news_correlation 不支持 output_brief 模式）\n'
        '  // ═══════════════════════════════════════════\n'
        '  "system_prompt_news_correlation": null,\n'
        '  "model_news_correlation": null,\n'
        '  "temperature_news_correlation": 0.1,\n'
        '  "max_tokens_news_correlation": 2000,\n'
        '  "timeout_news_correlation": 60,\n'
        '  "cache_enabled_news_correlation": true,\n'
        '  "thinking_enabled_news_correlation": false,\n'
        '  "thinking_budget_news_correlation": 4000,\n'
        '  "reasoning_effort_news_correlation": "high",\n'
        '  "news_correlation_top_n": 30,\n'
        '\n'
        '  // ═══════════════════════════════════════════\n'
        '  // 计价配置（默认使用 constants.py MODEL_PRICING，此处可覆盖）\n'
        '  // ═══════════════════════════════════════════\n'
        '  "pricing": {\n'
        '    "currency": "CNY",\n'
        '    "claude-sonnet-4-6": {"input": 3.0, "output": 15.0, "input_cache_hit": 0.3}\n'
        '  }\n'
        '}\n'
    )
